apiVersion: skaffold/v2beta21
kind: Config

build:
  tagPolicy:
    customTemplate:
      template: "0.0.1-SNAPSHOT"
  artifacts:
#    - image: tzolov/streaming-runtime
#      buildpacks:
#        builder: paketobuildpacks/builder:tiny
#        env:
#          - BP_NATIVE_IMAGE=true
    - image: tzolov/streaming-runtime
      custom:
        buildCommand: |
          ./mvnw clean install -Pnative -DskipTests spring-boot:build-image
deploy:
  kubectl:
    manifests:
      - ./streaming-runtime-crds/cluster-stream-crd.yaml
      - ./streaming-runtime-crds/stream-crd.yaml
    flags:
      apply:
        - --force
  kustomize:
    paths:
      - manifests