apiVersion: apps/v1
kind: Deployment
metadata:
  name: uppercase-with-multibinder-grpc
  labels:
    app: uppercase-with-multibinder-grpc
    type: streaming-spike
    component: uppercase-with-multibinder-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uppercase-with-multibinder-grpc
  template:
    metadata:
      labels:
        app: uppercase-with-multibinder-grpc
        component: uppercase-with-multibinder-grpc
    spec:
      containers:
        - name: multibinder-grpc
          image: tzolov/poc-multibinder-grpc:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_FUNCTION_GRPC_PORT
              value: "55554"
            - name: SPRING_CLOUD_FUNCTION_GRPC_SERVER
              value: "false"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10