apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-runtime
spec:
  selector:
    matchLabels:
      app: streaming-runtime
  template:
    metadata:
      labels:
        app: streaming-runtime
    spec:
      serviceAccountName: streaming-runtime
      containers:
        - name: cluster-stream-operator
          image: tzolov/streaming-runtime:0.0.1-SNAPSHOT
          env:
            - name: STREAMINGRUNTIME_NAMESPACE
              value: streaming-runtime
            - name: STREAMINGRUNTIME_CONFIGMAPKEY
              value: application-streams.yaml
            - name: LOGGING_COM_VMWARE_TANZU_STREAMING_RUNTIME
              value: debug
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
