apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: streaming-runtime
commonLabels:
  app.kubernetes.io/part-of: streaming-runtime

resources:
  - streaming-runtime-namespace.yaml
  - cluster-stream-deployment.yaml
  - streaming-runtime-cluster-role.yaml
  - streaming-runtime-cluster-role-binding.yaml
  - streaming-runtime-namespaced-role.yaml
  - streaming-runtime-namespaced-role-binding.yaml
  - streaming-runtime-account.yaml