apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: streaming-runtime-resource-role
  namespace: streaming-runtime
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - patch

  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - configmaps
    verbs:
      - list
      - create
      - update
      - watch