apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: ClusterStream
metadata:
  name: my-rabbitmq-cluster-stream
spec:
  keys: ["truckclass", "truckid"]
  streamModes: ["read", "write"]
  storage:
    servers:
    - url: "http://localhost:8080"
      protocol: "rabbitmq"
    attributes:
      key1: "value1"
    reclaimPolicy: "Retain"
