apiVersion: streaming.tanzu.vmware.com/v1alpha1
kind: Stream
metadata:
  name: my-kafka-stream
spec:
  keys: ["truckclass", "truckid"]
  streamMode: ["read"]
  protocol: "kafka"
  storage:
    clusterStream: "my-kafka-cluster-stream"
